os: osx
osx_image: xcode11.5
language: swift
script: xcodebuild clean build test -workspace NewsAm.xcworkspace -scheme "NewsAm" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.5' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
